### ISSUE TITLE
Overflow in checking process

### ISSUE THREAD

**Issue by isaacngym** [nsg-ethz/synet#2]
On a machine with 64GB:

`./synet.py -i examples/simple.logic -r examples/simple-req.logic -m bgp»simple.log`

Failed with the error:

```Traceback (most recent call last):
  File "./synet.py", line 56, in <module>
    main()
  File "./synet.py", line 47, in main
    syn.synthesize()
  File "/home/isaac_ng/synet/synet/synthesis3.py", line 484, in synthesize
    if solver.check() == z3.sat:
  File "/home/isaac_ng/miniconda2/envs/isaac1/lib/python2.7/site-packages/z3/z3.py", line 6626, in check
    r = Z3_solver_check_assumptions(self.ctx.ref(), self.solver, num, _assumptions)
  File "/home/isaac_ng/miniconda2/envs/isaac1/lib/python2.7/site-packages/z3/z3core.py", line 3714, in Z3_solver_check_assumptions
    _elems.Check(a0)
  File "/home/isaac_ng/miniconda2/envs/isaac1/lib/python2.7/site-packages/z3/z3core.py", line 1374, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: Overflow encountered when expanding old_vector
```

The log is not particularly informative. 
[simple.log](https://github.com/nsg-ethz/synet/files/3264606/simple.log) 

Steps taken to replicate:
1. Installed miniconda  
2. Installed Z3
3. Installed reqs
4. `./synet.py -i examples/simple.logic -r examples/simple-req.logic -m bgp»simple.log`

Is this the correct order and is there some config I am not setting before I begin?

**Comment by ahassany** [comment]
I don't quite get why minicoda is used (I actually don't know that package).

What version of z3 are you using? I would recommend to use a version prior to Dec 2017 as z3 change a bit since then.

**Comment by isaacngym** [comment]
Miniconda is a lightweight version of conda - I use it as my venv manager. I've never heard of it causing issues, but I'll try testing without it if need be.

I'm using the most updated version. When you say prior to Dec 2017 do you mean [version 4.5.0](https://github.com/Z3Prover/z3/releases/tag/z3-4.5.0)?

**Comment by ahassany** [comment]
Version 4.7.1 works.

**Comment by isaacngym** [comment]
Closing as I no longer need to run synet. Appreciate the effort to test a version, though.
